import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UButton, UCenter, UInput, USelect, USwitch, UText, UTitle } from "@sleek-ui/widgets.slint";
import { USelectOption } from "@sleek-ui/utils/structs.slint";

import { TemplatePage } from "../components/template_page.slint";
import { SettingLine } from "../components/setting-line.slint";
import { ComboBox } from "std-widgets.slint";


export global SettingsPageLogic {
    pure callback get-default-interpreter() -> string;
    pure callback get-notif-timeout() -> int;
    pure callback get-timeout-enabled() -> bool;
    pure callback get-language-current-index(options: [USelectOption]) -> int;
    pure callback get-scale-factor-current-index(options: [USelectOption]) -> int;
    callback save-settings(def-inter: string, lang: string, sf: float, timeout: int, tt-enabled: bool);
}

export component SettingsPage inherits TemplatePage {
    property <bool> settings-modified: false;
    HorizontalLayout {
        alignment: start;
        UTitle {
            text: @tr("General");
            level: 5;
            font-weight: 600;
        }
    }

    SettingLine {
        name: @tr("Zoom");
        description: @tr("Manage the zoom of the window.");
        scale-factor-select := USelect {
            property <[USelectOption]> options-data: [
                { text: SettingsTR.get-scale-factor-string(0.5), value: "0.5", enabled: true },
                { text: SettingsTR.get-scale-factor-string(0.75), value: "0.75", enabled: true },
                { text: SettingsTR.get-scale-factor-string(0.9), value: "0.9", enabled: true },
                { text: SettingsTR.get-scale-factor-string(1), value: "1", enabled: true },
                { text: SettingsTR.get-scale-factor-string(1.1), value: "1.1", enabled: true },
                { text: SettingsTR.get-scale-factor-string(1.25), value: "1.25", enabled: true },
                { text: SettingsTR.get-scale-factor-string(1.5), value: "1.5", enabled: true },
                { text: SettingsTR.get-scale-factor-string(1.75), value: "1.75", enabled: true },
                { text: SettingsTR.get-scale-factor-string(2), value: "2", enabled: true },
            ];
            width: 150px * UAppTheme.scale-factor;
            current-index: SettingsPageLogic.get-scale-factor-current-index(options-data);
            options: options-data;
            selected-changed(value) => {
                settings-modified = true;
            }
        }
    }

    SettingLine {
        name: @tr("Language");
        description: @tr("Change the language of the application.");
        language-select := USelect {
            property <[USelectOption]> options-data: [
                { text: SettingsTR.get-language-string("en_GB"), value: "en_GB", enabled: true },
                { text: SettingsTR.get-language-string("fr"), value: "fr", enabled: true },
            ];
            width: 150px * UAppTheme.scale-factor;
            current-index: SettingsPageLogic.get-language-current-index(options-data);
            options: options-data;
            selected-changed(value) => {
                settings-modified = true;
            }
        }
    }

    HorizontalLayout {
        alignment: start;
        padding-top: 24px * UAppTheme.scale-factor;
        UTitle {
            text: @tr("Scripts");
            level: 5;
            font-weight: 600;
        }
    }

    SettingLine {
        name: @tr("Auto-close notification");
        description: @tr("If enabled, the notifications will automatically close after a specified delay.");
        enable-timeout := USwitch {
            checked: SettingsPageLogic.get-timeout-enabled();
            changed checked => {
                settings-modified = true;
            }
        }
    }

    SettingLine {
        name: @tr("Auto-close delay");
        description: @tr("The delay before notification are automatically closed.");
        notif-timeout-input := UInput {
            width: 150px * UAppTheme.scale-factor;
            text: SettingsPageLogic.get-notif-timeout();
            input-type: number;
            enabled: enable-timeout.checked;
            edited => {
                settings-modified = true;
            }
        }
    }

    SettingLine {
        name: @tr("Default interpreter");
        description: @tr("This is the interpreter that is selected by default when adding a script.");
        default-interpreter-input := UInput {
            width: 150px * UAppTheme.scale-factor;
            text: SettingsPageLogic.get-default-interpreter();
            edited => {
                settings-modified = true;
            }
        }
    }

    Rectangle {
        vertical-stretch: 1;
    }

    UCenter {
        UButton {
            text: @tr("Save");
            variant: primary;
            enabled: settings-modified;
            clicked => {
                SettingsPageLogic.save-settings(
					default-interpreter-input.text,
					language-select.options[language-select.current-index].value,
					scale-factor-select.options[scale-factor-select.current-index].value.to-float(),
					notif-timeout-input.text.to-float(),
					enable-timeout.checked,
				);
                settings-modified = false;
            }
        }
    }
}

global SettingsTR {
    pure public function get-scale-factor-string(scale-factor: float) -> string {
        if scale-factor == 0.5 {
            return @tr("50%");
        }
        if scale-factor == 0.75 {
            return @tr("75%");
        }
        if scale-factor == 0.9 {
            return @tr("90%");
        }
        if scale-factor == 1 {
            return @tr("100%");
        }
        if scale-factor == 1.1 {
            return @tr("110%");
        }
        if scale-factor == 1.25 {
            return @tr("125%");
        }
        if scale-factor == 1.5 {
            return @tr("150%");
        }
        if scale-factor == 1.75 {
            return @tr("175%");
        }
        if scale-factor == 2 {
            return @tr("200%");
        }
        return @tr("Unknown");
    }
    pure public function get-language-string(language: string) -> string {
        if language == "en_GB" {
            return @tr("English");
        }
        if language == "fr" {
            return @tr("French");
        }
        return @tr("Unknown");
    }
}
