import "../assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf";
import "../assets/fonts/Inter-VariableFont_opsz,wght.ttf";

import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UText } from "@sleek-ui/widgets/text.slint";

import { ScrollView } from "std-widgets.slint";

import { Script } from "../structs.slint";


export component ScriptOutputWindow inherits Window {
    in-out property <[Script]> scripts;
    in-out property <int> script_index;
    property <Script> script: scripts[script_index];
    title: @tr("Output - ") + script.name;
    icon: @image-url("../../res/linux/32x32.png");
    default-font-family: "Inter";
    default-font-size: 14px * UAppTheme.scale-factor;
    min-width: 500px;
    min-height: 500px;
    background: UAppTheme.bg-container;
    ScrollView {
        width: 100%;
        height: 100%;
        viewport-height: script.output-lines.length * UAppTheme.font-size-base;
        VerticalLayout {
            alignment: start;
            for line in script.output-lines: UText {
                text: line;
                wrap: word-wrap;
            }
        }
    }
}
