import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UButton, UDivider, UText } from "@sleek-ui/widgets.slint";
import { Button } from "std-widgets.slint";
import { ButtonInterface } from "@sleek-ui/utils/button-interface.slint";


export global HeaderStatus {
    in-out property <string> current-page: "home";
}

export component Header inherits Rectangle {
    property <[{text: string, page: string}]> links: [
        { text: @tr("Home"), page: "home" },
        { text: @tr("Settings"), page: "settings" },
        { text: @tr("About"), page: "about" },
    ];
    property <length> current-link-width;
    property <length> current-link-x;
    callback open-add-script-modal <=> add-script-btn.clicked;
    height: 50px * UAppTheme.scale-factor;
    background: UAppTheme.bg-container;
    drop-shadow-color: UAppTheme.shadow-color;
    drop-shadow-blur: 8px * UAppTheme.scale-factor;
    HorizontalLayout {
        alignment: space-between;
        padding: UAppTheme.padding-big;
        HorizontalLayout {
            spacing: 32px * UAppTheme.scale-factor;
            for link in links: ButtonInterface {
                link-text := UText {
                    text: link.text;
                    animate color { duration: 200ms; }
                    states [
                        selected when HeaderStatus.current-page == link.page: {
                            color: UAppTheme.primary;
                        }
                        hover when parent.has-hover: {
                            color: UAppTheme.primary-hover;
                        }
                    ]
                }

                clicked => {
                    current-link-width = self.width;
                    current-link-x = self.x;
                    HeaderStatus.current-page = link.page;
                }
                Timer {
                    running: true;
                    interval: 1ms;
                    triggered => {
                        current-link-width = parent.width;
                        current-link-x = parent.x;
                        self.running = false;
                    }
                }
            }
        }

        VerticalLayout {
            alignment: center;
            add-script-btn := UButton {
                text: @tr("Add a script");
                variant: primary;
                icon: @image-url("../assets/icons/plus.svg");
                icon-placement: start;
            }
        }
    }

    Rectangle {
        x: current-link-x + UAppTheme.padding-big;
        y: 42px * UAppTheme.scale-factor;
        height: 2px;
        background: UAppTheme.primary;
        width: current-link-width;
        animate x, width { duration: 150ms; }
    }
}
