import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UButton, UCheckbox, UIconButton, UModal, UInput, UText } from "@sleek-ui/widgets.slint";

import { Script } from "../structs.slint";


export global ScriptSettingsModalLogic {
    callback delete-script(script_index: int);
    callback save-script-settings(id: string, name: string, interpreter: string, args: string, admin: bool, notif: bool);
}

export component ScriptSettingsModal inherits UModal {
    in-out property <Script> script;
    in-out property <int> script_index;
    t-modal-min-width: 500px * UAppTheme.scale-factor;
    t-modal-max-width: 500px * UAppTheme.scale-factor;
    title: @tr("Settings - ") + script.name;
    accept-btn-text: @tr("Save");
    accept-btn-enabled: name-input.text != "" && interpreter-input.text != "";
    accepted => {
        ScriptSettingsModalLogic.save-script-settings(
			script.id,
			name-input.text,
			interpreter-input.text,
			args-input.text,
			need-admin-checkbox.checked,
			notifs-checkbox.checked,
		);
    }
    VerticalLayout {
        GridLayout {
            spacing: UAppTheme.spacing-big;
            Row {
                VerticalLayout {
                    alignment: center;
                    UText {
                        text: @tr("Name:");
                    }
                }

                name-input := UInput {
                    horizontal-stretch: 1;
                    text: script.name;
                }
            }

            Row {
                VerticalLayout {
                    alignment: center;
                    UText {
                        text: @tr("Interpreter:");
                    }
                }

                interpreter-input := UInput {
                    horizontal-stretch: 1;
                    text: script.interpreter;
                }
            }

            Row {
                VerticalLayout {
                    alignment: center;
                    UText {
                        text: @tr("Arguments:");
                    }
                }

                args-input := UInput {
                    horizontal-stretch: 1;
                    text: script.args;
                }
            }

            Row {
                VerticalLayout {
                    alignment: center;
                    UText {
                        text: @tr("Administrator:");
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                    HorizontalLayout {
                        alignment: start;
                        need-admin-checkbox := UCheckbox {
                            checked: script.need-admin;
                            enabled: Platform.os == OperatingSystemType.linux;
                        }
                    }
                }
            }

            Row {
                VerticalLayout {
                    alignment: center;
                    UText {
                        text: @tr("Notifications:");
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;
                    HorizontalLayout {
                        alignment: start;
                        notifs-checkbox := UCheckbox {
                            checked: script.notifs-enabled;
                        }
                    }
                }
            }
        }

        HorizontalLayout {
            alignment: end;
            UButton {
                danger: true;
                text: @tr("Delete");
                accessible-label: @tr("Delete the script.");
                clicked => {
                    ScriptSettingsModalLogic.delete-script(script_index);
                    root.close();
                }
            }
        }
    }
}
