import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UCard } from "@sleek-ui/widgets.slint";
import { ScrollView } from "std-widgets.slint";


export component TemplatePage {
    vertical-stretch: 1;
    ScrollView {
        VerticalLayout {
            padding: UAppTheme.padding-big;
            HorizontalLayout {
                alignment: center;
                UCard {
                    width: 600px * UAppTheme.scale-factor;
                    VerticalLayout {
                        padding: UAppTheme.padding-big;
                        spacing: UAppTheme.spacing-big;
                        vertical-stretch: 1;
                        @children
                    }
                }
            }
        }
    }
}
