import { UAppTheme } from "../../app-theme.slint";


export enum UIconButtonType {
	primary,
	default,
	filled,
	text,
}

export struct UIconButtonTheme {
	background: color,
	background-hover: color,
	background-active: color,
	background-disabled: color,
	text-color: color,
	text-color-hover: color,
	text-color-active: color,
	text-color-disabled: color,
	border-width: length,
	border-radius: length,
	border: color,
	border-hover: color,
	border-active: color,
	border-disabled: color,
	padding-vertical: length,
	padding-horizontal: length,
	font-size: length,
}

export global UIconButtonThemes {
    public pure function get-theme(type: UIconButtonType, danger: bool) -> UIconButtonTheme {
        if type == UIconButtonType.default {
            return danger ? default-danger : default;
        } else if type == UIconButtonType.filled {
            return danger ? filled-danger : filled;
        } else if type == UIconButtonType.text {
            return danger ? text-danger : text;
        }
		// Returning primary as it is the default value.
        return danger ? primary-danger : primary;
    }
    out property <UIconButtonTheme> primary: {
        background: UAppTheme.primary,
        background-hover: UAppTheme.primary-hover,
        background-active: UAppTheme.primary-active,
        background-disabled: UAppTheme.border-secondary,
        text-color: Colors.white,
        text-color-hover: Colors.white,
        text-color-active: Colors.white,
        text-color-disabled: UAppTheme.text-disabled,
        border-width: 1px,
        border-disabled: UAppTheme.border,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> default: {
        background: UAppTheme.bg-container,
        background-hover: UAppTheme.color-fill-secondary,
        background-active: UAppTheme.color-fill,
        background-disabled: UAppTheme.border-secondary,
        text-color:  UAppTheme.text,
        text-color-hover: UAppTheme.text,
        text-color-active: UAppTheme.text,
        text-color-disabled: UAppTheme.text-disabled,
        border-width: 1px,
        border:  UAppTheme.border,
        border-hover: UAppTheme.border,
        border-active: UAppTheme.border,
        border-disabled: UAppTheme.border,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> filled: {
        background: UAppTheme.color-fill-tertiary,
        background-hover: UAppTheme.color-fill-secondary,
        background-active: UAppTheme.color-fill,
        text-color: UAppTheme.text,
        text-color-hover: UAppTheme.text,
        text-color-active: UAppTheme.text,
        text-color-disabled: UAppTheme.text-disabled,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> text: {
        background-hover: UAppTheme.color-fill-secondary,
        background-active: UAppTheme.color-fill,
        text-color: UAppTheme.text,
        text-color-hover: UAppTheme.text,
        text-color-active: UAppTheme.text,
        text-color-disabled: UAppTheme.text-disabled,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> primary-danger: {
        background: UAppTheme.danger,
        background-hover: UAppTheme.danger-hover,
        background-active: UAppTheme.danger-active,
        background-disabled: UAppTheme.border-secondary,
        text-color: Colors.white,
        text-color-hover: Colors.white,
        text-color-active: Colors.white,
        text-color-disabled: UAppTheme.text-disabled,
        border-width: 1px,
        border-disabled: UAppTheme.border,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> default-danger: {
        background-hover: UAppTheme.danger-selected,
        background-active: UAppTheme.danger-selected.darker(0.05),
        background-disabled: UAppTheme.border-secondary,
        text-color: UAppTheme.danger,
        text-color-hover: UAppTheme.danger-hover,
        text-color-active: UAppTheme.danger-active,
        text-color-disabled: UAppTheme.text-disabled,
        border-width: 1px,
        border: UAppTheme.danger,
        border-hover: UAppTheme.danger-hover,
        border-active: UAppTheme.danger-active,
        border-disabled: UAppTheme.border,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> filled-danger: {
        background: UAppTheme.danger.with-alpha(0.1),
        background-hover: UAppTheme.danger-hover.with-alpha(0.3),
        background-active: UAppTheme.danger-active.with-alpha(0.4),
        text-color: UAppTheme.danger,
        text-color-hover: UAppTheme.danger-hover,
        text-color-active: UAppTheme.danger-active,
        text-color-disabled: UAppTheme.text-disabled,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
    out property <UIconButtonTheme> text-danger: {
        background-hover: UAppTheme.danger-hover.with-alpha(0.1),
        background-active: UAppTheme.danger-active.with-alpha(0.3),
        text-color: UAppTheme.danger,
        text-color-hover: UAppTheme.danger-hover,
        text-color-active: UAppTheme.danger-active,
        text-color-disabled: UAppTheme.text-disabled,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-vertical * 1.1,
        font-size: UAppTheme.default-font-size,
        border-radius: UAppTheme.default-radius,
    };
}
