import { UAppTheme } from "../../app-theme.slint";
import { Palette } from "std-widgets.slint";


export component UPopover inherits PopupWindow {
    in-out property <length> default-border-radius: UAppTheme.default-radius > 4px ? 4px : UAppTheme.default-radius;
    min-height: 10px;
    Rectangle {
        width: 100%;
        height: 100%;
        background: UAppTheme.bg-elevated;
        border-radius: root.default-border-radius;
        drop-shadow-color: Palette.color-scheme != ColorScheme.dark ? UAppTheme.border : transparent;
        drop-shadow-blur: 10px;
        VerticalLayout {
            alignment: start;
            padding: 4px;
            @children
        }
    }
}
