import { UInputType, UInputTheme, UInputThemes } from "theme.slint";
import { UAppTheme } from "../../app-theme.slint";
import { UIcon } from "../icon/icon.slint";


export component UInput inherits Rectangle {
    in-out property <UInputType> type: UInputType.base;
    property <UInputTheme> theme: UInputThemes.get-theme(type);
    in-out property <string> text <=> input.text;
    in-out property <bool> enabled <=> input.enabled;
    in-out property <InputType> input-type: InputType.text;
    in-out property <string> placeholder: "";
    in-out property <bool> clearable: false;
    in-out property <bool> error: false;
    in-out property <bool> show: false;
    border-width: theme.border-width;
    border-radius: theme.border-radius;
    border-color: theme.border-color;
    background: theme.background;
    clip: true;
    HorizontalLayout {
        width: root.width;
        HorizontalLayout {
            padding-left: root.theme.padding-horizontal;
            padding-right: root.theme.padding-horizontal;
            Rectangle {
                height: root.theme.font-size + root.theme.padding-vertical * 3;
                clip: true;
                input := TextInput {
                    property <length> h-padding: root.theme.padding-horizontal * 2;
                    property <length> computed_x;
                    width: max(parent.width, self.preferred-width);
                    x: min(computed_x, 0px);
                    input-type: root.input-type;
                    read-only: !root.enabled;
                    font-size: root.theme.font-size;
                    font-weight: root.theme.font-weight;
                    color: root.theme.text-color;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    single-line: true;
                    wrap: no-wrap;
					// Shamelessly taken from Surrealisme UI
					// Source : https://github.com/Surrealism-All/SurrealismUI/blob/main/src/input/input.slint
					cursor-position-changed(cpos) => {
                        if cpos.x + self.computed_x < self.h-padding {
                            self.computed_x = - cpos.x + self.h-padding;
                        } else if cpos.x + self.computed_x > parent.width - 1px {
                            self.computed_x = parent.width - cpos.x - 1px;
                        }
                    }
                    if self.text == "" && root.placeholder != "": HorizontalLayout {
                        alignment: start;
                        VerticalLayout {
                            alignment: center;
                            Text {
                                text: root.placeholder;
                                color: root.theme.placeholder-color;
                                font-size: root.theme.font-size;
                                font-weight: root.theme.font-weight;
                            }
                        }
                    }
                }
            }
        }

        if clearable && root.input-type != InputType.password: VerticalLayout {
            alignment: center;
            padding-left: -root.theme.padding-horizontal;
            Rectangle {
                height: 100%;
                width: root.theme.icon-size + root.theme.padding-horizontal;
                UIcon {
                    size: root.theme.icon-size;
                    colorize: root.theme.icon-color;
                    source: @image-url("../../assets/images/circle-x.svg");
                }

                TouchArea {
                    mouse-cursor: MouseCursor.pointer;
                    clicked => {
                        root.text = "";
                        input.set-selection-offsets(0, 0);
                    }
                }
            }
        }
        if root.input-type == InputType.password: VerticalLayout {
            alignment: center;
            padding-left: -root.theme.padding-horizontal;
            Rectangle {
                height: 100%;
                width: root.theme.icon-size + root.theme.padding-horizontal;
                UIcon {
                    size: root.theme.icon-size;
                    colorize: root.theme.icon-color;
                    source: root.show ? @image-url("../../assets/images/eye.svg") : @image-url("../../assets/images/eye-closed.svg");
                }

                TouchArea {
                    mouse-cursor: MouseCursor.pointer;
                    clicked => {
                        root.show = !root.show;
                        if root.show {
                            input.input-type = InputType.text;
                        } else {
                            input.input-type = InputType.password;
                        }
                    }
                }
            }
        }
    }

    states [
        disabled when !input.enabled: {
            background: theme.background-disabled;
            border-color: theme.border-color-disabled;
        }
        error when error: {
            background: theme.background-error;
            border-color: theme.border-color-error;
        }
        active when input.has-focus: {
            background: theme.background-active;
            border-color: theme.border-color-active;
        }
    ]

	// Link the functions and callback of TextInput to child.
	public function set-selection-offsets(start: int, end: int) {
        input.set-selection-offsets(start, end);
    }
    public function select-all() {
        input.select-all();
    }
    public function clear-selection() {
        input.clear-selection();
    }
    public function copy() {
        input.copy();
    }
    public function cut() {
        input.cut();
    }
    public function paste() {
        input.paste();
    }
    callback accepted <=> input.accepted;
    callback cursor-position-changed <=> input.cursor-position-changed;
    callback edited <=> input.edited;
    callback key-pressed <=> input.key-pressed;
    callback key-released <=> input.key-released;
}
