import { UAppTheme } from "../../app-theme.slint";


export enum UInputType {
	base,
}

export struct UInputTheme {
	background: color,
	background-active: color,
	background-error: color,
	background-disabled: color,
	border-width: length,
	border-radius: length,
	border-color: color,
	border-color-error: color,
	border-color-active: color,
	border-color-disabled: color,
	text-color: color,
	font-size: length,
	font-weight: int,
	placeholder-color: color,
	icon-size: length,
	icon-color: color,
	padding-vertical: length,
	padding-horizontal: length,
}


export global UInputThemes {
    public pure function get-theme(type: UInputType) -> UInputTheme {
        return base;
    }
    out property <UInputTheme> base: {
        background: UAppTheme.bg-elevated,
        background-active: UAppTheme.bg-elevated,
        background-error: UAppTheme.bg-elevated,
        background-disabled: UAppTheme.color-fill-quaternary,
        border-width: 1px,
        border-radius: UAppTheme.default-radius,
        border-color: UAppTheme.border,
        border-color-active: UAppTheme.primary-active,
        border-color-error: UAppTheme.danger,
        border-color-disabled: UAppTheme.border-secondary,
        text-color: UAppTheme.text,
        font-size: UAppTheme.default-font-size,
        placeholder-color: UAppTheme.text-disabled,
        icon-size: UAppTheme.default-font-size,
        icon-color: UAppTheme.text-secondary,
        padding-vertical: UAppTheme.padding-vertical,
        padding-horizontal: UAppTheme.padding-horizontal / 2,
    };
}
