import { UAppTheme } from "../../app-theme.slint";

export component UTitle inherits Text {
    in property <int> level: 1;
    states [
        _ when level == 1: {
            color: UAppTheme.text-heading;
            font-size: 36px;
            font-weight: 600;
        }
        _ when level == 2: {
            color: UAppTheme.text-heading;
            font-size: 30px;
            font-weight: 500;
        }
        _ when level == 3: {
            color: UAppTheme.text-heading;
            font-size: 24px;
            font-weight: 400;
        }
        _ when level == 4: {
            color: UAppTheme.text-heading;
            font-size: 20px;
            font-weight: 400;
        }
        _ when level == 5: {
            color: UAppTheme.text-heading;
            font-size: 18px;
            font-weight: 400;
        }
        _ when level == 6: {
            color: UAppTheme.text-heading;
            font-size: 16px;
            font-weight: 400;
        }
    ]
}
