import "assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf";
import "assets/fonts/Inter-VariableFont_opsz,wght.ttf";

// UI library
import { UAppTheme } from "@sleek-ui/app-theme.slint";
import { UModal } from "@sleek-ui/widgets.slint";

// Components
import { Header, HeaderStatus } from "components/header.slint";
import { AddScriptModal, AddScriptModalLogic } from "components/add-script-modal.slint";
import { ScriptSettingsModal, ScriptSettingsModalLogic } from "components/script-settings-modal.slint";
import {
	NotificationsOverlay,
	NotifsOverlayLogic,
	NotifTypeEnum,
	NotifStringEnum
} from "components/notifications-overlay.slint";

// Pages
import { AboutPage, AboutPageLogic } from "pages/about.slint";
import { MainPage, MainPageLogic } from "pages/main.slint";
import { SettingsPage, SettingsPageLogic } from "pages/settings.slint";


export component Scriptboard inherits Window {
    title: "Scriptboard";
    icon: @image-url("../res/linux/32x32.png");
    default-font-family: "Inter";
    default-font-size: 14px * UAppTheme.scale-factor;
    min-width: 700px;
    min-height: 400px;
    preferred-width: 1000px;
    preferred-height: 550px;
    background: UAppTheme.bg-layout;
    VerticalLayout {
        alignment: stretch;
        Header {
            height: 40px * UAppTheme.scale-factor;
            vertical-stretch: 0;
            open-add-script-modal => {
                add-script-modal.show();
            }
        }

        if HeaderStatus.current-page == "main": main-page := MainPage {
            open-script-settings(script, script_index) => {
                script-settings.script = script;
                script-settings.script_index = script_index;
                script-settings.show();
            }
        }
        if HeaderStatus.current-page == "settings": SettingsPage { }
        if HeaderStatus.current-page == "about": AboutPage { }
    }

    notification-overlay := NotificationsOverlay { }

    add-script-modal := AddScriptModal { }

    script-settings := ScriptSettingsModal { }
}

export { 
	UAppTheme,
	AddScriptModalLogic,
	ScriptSettingsModalLogic,
	AboutPageLogic,
	MainPageLogic,
	SettingsPageLogic,
	NotifsOverlayLogic,
	NotifTypeEnum,
	NotifStringEnum
}
export { ScriptOutputWindow } from "windows/script_output_window.slint";