import { AppTheme } from "@sleek-ui/app-themes/app-theme-struct.slint";

export global ScriptboardThemes {
    out property <AppTheme> default-theme: {
        // Primary
        primary: #9549ff,
        primary-hover: #b273ff,
        primary-active: #7334d9,
        primary-disabled: #cc9cff,
        primary-selected: #f9f0ff,

        // Success
        success: #52c41a,
        success-hover: #73d13d,
        success-active: #389e0d,
        success-disabled: #95de64,
        success-selected: #f6ffed,

        // Warning
        warning: #faad14,
        warning-hover: #ffc53d,
        warning-active: #d48806,
        warning-disabled: #ffd666,
        warning-selected: #fffbe6,

        // Danger
        danger: #ff4d4f,
        danger-hover: #ff7875,
        danger-active: #d9363e,
        danger-disabled: #ff7875,
        danger-selected: #fff1f0,

        // Background color
        bg-layout: #F5F5F5,
        bg-container: Colors.white,
        bg-elevated: Colors.white,
        bg-inverse: #262626,

        // Color fill
        color-fill-plus: rgba(0, 0, 0, 0.25),
        color-fill: rgba(0, 0, 0, 0.15),
        color-fill-secondary: rgba(0, 0, 0, 0.06),
        color-fill-tertiary: rgba(0, 0, 0, 0.04),
        color-fill-quaternary: rgba(0, 0, 0, 0.02),

        // Shadow
        shadow-color: rgba(0, 0, 0, 0.12),
        shadow-blur: 16px,
        shadow-x-offset: 0px,
        shadow-y-offset: 6px,

        // Text color
        inverse-text: rgba(255,255,255,0.85),
        text: #000000E0,
        text-secondary: #000000A6,
        text-heading: #000000E0,
        text-disabled: #00000040,

        // Font size
        font-size-smaller: 10px,
        font-size-small: 12px,
        font-size-base: 14px,
        font-size-medium: 16px,
        font-size-big: 18px,
        font-size-bigger: 20px,
  
        // Focus display
        focus-color: Colors.black,
        focus-border-width: 2px,

        // Borders
        border-width-base: 1px,
        border: #D9D9D9,
        border-secondary: #f0f0f0,
        separator: #0505050F,

        // Icons
        icon-size-base: 16px,

        // Padding
        padding-vertical: 5px,
        padding-horizontal: 14px,
        padding-small: 2px,
        padding-base: 4px,
        padding-medium: 8px,
        padding-big: 12px,
        padding-bigger: 16px,

        // Spacing
        spacing-small: 2px,
        spacing-base: 4px,
        spacing-medium: 8px,
        spacing-big: 12px,
        spacing-bigger: 16px,

        // Radius
        radius-base: 4px,
        radius-small: 2px,
        radius-medium: 4px,
        radius-large: 8px,
        radius-round: 20px,
        radius-circle: 9999px,
    };
}
